import io, os

PATH = "/opt/GalxeMonitor/combined_app.py"

if not os.path.exists(PATH):
    print("❌ 找不到", PATH)
    raise SystemExit(1)

with io.open(PATH, "r", encoding="utf-8") as f:
    src = f.readlines()

start = None
end = None

# 以 @app.route("/manage") 为锚点，整块替换
for i, line in enumerate(src):
    if line.strip().startswith('@app.route("/manage"'):
        start = i
        break

if start is None:
    print("❌ 文件里没有找到 @app.route(\"/manage\")，不做修改")
    raise SystemExit(1)

for j in range(start + 1, len(src)):
    if src[j].startswith('@app.route("'):
        end = j
        break

if end is None:
    end = len(src)

new_block = [
'@app.route("/manage")\n',
'def manage():\n',
'    """项目管理页面：深色 UI + 表格 + 添加/删除操作"""\n',
'    cfg = load_config()\n',
'    pwd = request.args.get("pwd", "")\n',
'    if pwd != cfg.get("webui_password"):\n',
'        return "Unauthorized", 401\n',
'\n',
'    rows = ""\n',
'    for i, p in enumerate(cfg.get("projects", [])):\n',
'        rows += "<tr>" \\\n',
'                 f"<td>{i}</td>" \\\n',
'                 f"<td>{p.get(\'name\', \'\')}</td>" \\\n',
'                 f"<td>{p.get(\'alias\', \'\')}</td>" \\\n',
'                 f"<td>{p.get(\'category\', \'custom\')}</td>" \\\n',
'                 "</tr>"\n',
'\n',
'    if not rows:\n',
'        rows = "<tr><td colspan=\\"4\\">暂无项目，请在下方添加。</td></tr>"\n',
'\n',
'    html = """\n',
'    <html>\n',
'    <head>\n',
'      <meta charset="utf-8" />\n',
'      <title>Galxe Monitor · 项目管理</title>\n',
'      <style>\n',
'        body {{\n',
'          margin: 0;\n',
'          padding: 0;\n',
'          background: #020617;\n',
'          color: #e5e7eb;\n',
'          font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;\n',
'        }}\n',
'        .container {{\n',
'          max-width: 960px;\n',
'          margin: 0 auto;\n',
'          padding: 20px 16px 40px;\n',
'        }}\n',
'        h1 {{\n',
'          margin: 0 0 6px;\n',
'          font-size: 24px;\n',
'        }}\n',
'        .subtitle {{\n',
'          font-size: 13px;\n',
'          color: #9ca3af;\n',
'          margin-bottom: 16px;\n',
'        }}\n',
'        a {{ color:#60a5fa; text-decoration:none; }}\n',
'        a:hover {{ text-decoration:underline; }}\n',
'        .card {{\n',
'          background: radial-gradient(circle at top left,#1f2937 0,#020617 45%);\n',
'          border-radius: 14px;\n',
'          border: 1px solid #111827;\n',
'          padding: 14px 16px 16px;\n',
'          box-shadow: 0 10px 25px rgba(0,0,0,0.45);\n',
'          margin-bottom: 14px;\n',
'        }}\n',
'        .card-header {{\n',
'          display:flex;\n',
'          justify-content:space-between;\n',
'          align-items:center;\n',
'          margin-bottom:10px;\n',
'        }}\n',
'        .card-title {{ font-size:15px; font-weight:600; }}\n',
'        .pill-back {{\n',
'          border-radius:999px;\n',
'          padding:4px 10px;\n',
'          font-size:12px;\n',
'          border:1px solid #374151;\n',
'          background:#020617;\n',
'        }}\n',
'        table {{\n',
'          width: 100%;\n',
'          border-collapse: collapse;\n',
'          font-size: 13px;\n',
'        }}\n',
'        th, td {{\n',
'          border-bottom: 1px solid #1f2937;\n',
'          padding: 6px 8px;\n',
'          text-align: left;\n',
'          white-space: nowrap;\n',
'        }}\n',
'        th {{\n',
'          font-weight:500;\n',
'          color:#9ca3af;\n',
'          background:#020617;\n',
'        }}\n',
'        tr:hover td {{\n',
'          background:#020617;\n',
'        }}\n',
'        .form-row {{\n',
'          display:flex;\n',
'          flex-wrap:wrap;\n',
'          gap:8px;\n',
'          align-items:center;\n',
'          margin-top:8px;\n',
'        }}\n',
'        .form-row label {{\n',
'          font-size:12px;\n',
'          color:#9ca3af;\n',
'        }}\n',
'        .form-row input {{\n',
'          background:#020617;\n',
'          border-radius:999px;\n',
'          border:1px solid #1f2937;\n',
'          padding:5px 10px;\n',
'          color:#e5e7eb;\n',
'          font-size:12px;\n',
'        }}\n',
'        .btn {{\n',
'          border-radius:999px;\n',
'          border:1px solid #4b5563;\n',
'          background:#111827;\n',
'          color:#e5e7eb;\n',
'          padding:6px 12px;\n',
'          font-size:12px;\n',
'          cursor:pointer;\n',
'        }}\n',
'        .btn-primary {{\n',
'          background:#10b981;\n',
'          border-color:#10b981;\n',
'          color:#022c22;\n',
'          font-weight:600;\n',
'        }}\n',
'        .hint {{\n',
'          font-size:11px;\n',
'          color:#9ca3af;\n',
'          margin-top:4px;\n',
'        }}\n',
'        @media (max-width:640px) {{\n',
'          .form-row {{ flex-direction:column; align-items:flex-start; }}\n',
'        }}\n',
'      </style>\n',
'    </head>\n',
'    <body>\n',
'      <div class="container">\n',
'        <h1>项目管理</h1>\n',
'        <div class="subtitle">\n',
'          在这里增删你要监控的 Galxe Space。完成后返回监控首页查看最新活动。\n',
'        </div>\n',
'\n',
'        <div class="card">\n',
'          <div class="card-header">\n',
'            <div class="card-title">当前已监控项目</div>\n',
'            <a class="pill-back" href="/?pwd={pwd}">← 返回监控首页</a>\n',
'          </div>\n',
'          <div style="overflow-x:auto;">\n',
'            <table>\n',
'              <tr><th>索引</th><th>名称</th><th>Alias</th><th>分类</th></tr>\n',
'              {rows}\n',
'            </table>\n',
'          </div>\n',
'        </div>\n',
'\n',
'        <div class="card">\n',
'          <div class="card-header">\n',
'            <div class="card-title">添加项目</div>\n',
'          </div>\n',
'          <form method="GET" action="/add">\n',
'            <input type="hidden" name="pwd" value="{pwd}">\n',
'            <div class="form-row">\n',
'              <label>名称</label>\n',
'              <input name="name" placeholder="例如：BNB Chain">\n',
'              <label>Alias</label>\n',
'              <input name="alias" placeholder="例如：bnbchain">\n',
'              <label>分类</label>\n',
'              <input name="category" value="custom" placeholder="custom 或 trending">\n',
'              <button type="submit" class="btn btn-primary">添加</button>\n',
'            </div>\n',
'            <div class="hint">Alias 通常可以从 Galxe Space URL 中看到（app.galxe.com/space/&lt;alias&gt;）。</div>\n',
'          </form>\n',
'        </div>\n',
'\n',
'        <div class="card">\n',
'          <div class="card-header">\n',
'            <div class="card-title">删除项目</div>\n',
'          </div>\n',
'          <form method="GET" action="/delete">\n',
'            <input type="hidden" name="pwd" value="{pwd}">\n',
'            <div class="form-row">\n',
'              <label>索引</label>\n',
'              <input name="idx" placeholder="在上表中查看索引，例如：0">\n',
'              <button type="submit" class="btn">删除</button>\n',
'            </div>\n',
'            <div class="hint">删除后自动保存，无需重启程序。</div>\n',
'          </form>\n',
'        </div>\n',
'      </div>\n',
'    </body>\n',
'    </html>\n',
'    """.format(rows=rows, pwd=cfg["webui_password"])\n',
'\n',
'    return html\n',
]

backup = PATH + ".bak_manage_ui"
with io.open(backup, "w", encoding="utf-8") as f:
    f.writelines(src)

with io.open(PATH, "w", encoding="utf-8") as f:
    f.writelines(src[:start] + new_block + src[end:])

print("✅ /manage 页面 UI 已替换为深色卡片版")
print("📦 旧版本已备份到:", backup)
